services:
  app:
    build: .
    image: myapp-php:8.2-apache-pg
    container_name: myapp
    working_dir: /var/www/html
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    environment:
      DB_DSN: pgsql:host=host.docker.internal;port=5432;dbname=myapp
      DB_USER: postgres
      DB_PASS: Ozgur16betul
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
